name: easysave
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  avatar_glow:
  shared_preferences: ^2.0.20
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.5.4
  firebase_auth: ^4.5.0
  firebase_core:
  firebase_database: ^10.1.2
  firebase_storage: ^11.1.2
  firebase_analytics:
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  path: ^1.8.2
  path_provider: ^2.0.14
  form_validator:
  fl_chart:
  sticky_grouped_list:
  syncfusion_flutter_charts:
  sn_progress_dialog: ^1.1.3
  sqflite:
  typewritertext: ^1.8.0
  simple_circular_progress_bar: ^1.0.2
  flutter_margin_widget:
  http: ^1.1.0

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1
  json_serializable: ^6.6.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ibm-plex-sans
      fonts:
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-BoldItalic.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-BoldItalic.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-ExtraLight.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-ExtraLightItalic.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-Italic.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-Light.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-Medium.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-LightItalic.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-MediumItalic.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-SemiBold.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-SemiBoldItalic.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-Thin.ttf
        - asset: assets/fonts/ibm-plex-sans/IBMPlexSans-ThinItalic.ttf
