import 'package:isar/isar.dart';
import 'package:json_annotation/json_annotation.dart';


part 'atsave_user.g.dart';

@collection
@JsonSerializable()

/// This class represents a person[ATSaveUser] who signs up with a first name, last name and email.
/// A [uid] is autogenerated on authentication by firebase and an [id] on isar collection.
class ATSaveUser {
  final String firstName;
  final String lastName;
  final String email;
  Id? id;
  final String uid;

/// Creates a new user with the given [firstName], [lastName], [id], [uid] and [email].
  ATSaveUser(
      {this.id,
      required this.firstName,
      required this.lastName,
      required this.email,
      required this.uid});

/// Method from Isar to save [ATSaveUser] to an isar object
  factory ATSaveUser.fromJson(Map<Object?, Object?> json) =>
      _$ATSaveUserFromJson(json);

  /// Connecting the generated [_$TechKidUserToJson] function to the `toJson` method.
  Map<Object?, Object?> toJson() => _$ATSaveUserToJson(this);
}
