import 'package:isar/isar.dart';
import 'package:json_annotation/json_annotation.dart';

part 'category.g.dart';

@collection
@JsonSerializable()

/// This class represents a person's [Category] for goals or expenses.
/// It is linked to a [ATSaveUser] with [uid] autogenerated on authentication by firebase and has am [id] on isar collection.
class Category {

  //variables of category
  Id? id;
  final String name;
  final String imagePath;

  Category({required this.name, required this.imagePath, this.id});

  factory Category.fromJson(Map<Object?, Object?> json) =>
      _$CategoryFromJson(json);

  /// Connect the generated [_$CategoryToJson] function to the `toJson` method.
  Map<Object?, Object?> toJson() => _$CategoryToJson(this);
}
