
import 'package:isar/isar.dart';
import 'package:json_annotation/json_annotation.dart';

part 'expenses.g.dart';

@collection
@JsonSerializable()


/// This class represents a person's [Expenses] from his savings.
/// It is linked to a [ATSaveUser] with [uid] autogenerated on authentication by firebase and has am [id] on isar collection.
class Expenses {

  //variables of expenses
  Id? id;
  final DateTime date;
  final double amountSpent;
  final int savingsId;
  final String uid;

  Expenses(
      {
       this.id, required this.amountSpent, required this.date, required this.savingsId, required this.uid});

  factory Expenses.fromJson(Map<Object?, Object?> json) =>
      _$ExpensesFromJson(json);

  /// Connect the generated [_$ExpensesToJson] function to the `toJson` method.
  Map<Object?, Object?> toJson() => _$ExpensesToJson(this);
}
