import 'package:isar/isar.dart';
import 'package:json_annotation/json_annotation.dart';

part 'savings_transactions.g.dart';

@collection
@JsonSerializable()


/// This class represents a person's [SavingsTransactions] which is saved whenever a user makes any transaction on his savings.
/// It is linked to a [ATSaveUser] with [uid] autogenerated on authentication by firebase and has am [id] on isar collection.
class SavingsTransactions {
  Id? id;
  final String uid;
  final DateTime timeStamp;
  int? savingsId;
  double? amountSaved;
  double? amountExpended;

  SavingsTransactions(
      {
        this.id,
        this.savingsId,
      required this.amountExpended,
      this.amountSaved,
      required this.timeStamp,
      required this.uid});

  factory SavingsTransactions.fromJson(Map<Object?, Object?> json) =>
      _$SavingsTransactionsFromJson(json);

  /// Connect the generated [_$SavingsTransactionsToJson] function to the `toJson` method.
  Map<Object?, Object?> toJson() => _$SavingsTransactionsToJson(this);
}
