// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiOljIZWylK7m8dsugCFCLaeeRymyd1w',
    appId: '1:932030323231:android:c3305c303ff59813e6532a',
    messagingSenderId: '932030323231',
    projectId: 'atsave-2db27',
    databaseURL: 'https://atsave-2db27-default-rtdb.firebaseio.com',
    storageBucket: 'atsave-2db27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChLOlkytYkyRYLdvqYqVbMbq7XjzPupPA',
    appId: '1:932030323231:ios:83ab0a489b880a61e6532a',
    messagingSenderId: '932030323231',
    projectId: 'atsave-2db27',
    databaseURL: 'https://atsave-2db27-default-rtdb.firebaseio.com',
    storageBucket: 'atsave-2db27.appspot.com',
    iosClientId: '932030323231-4ktus5d7njhduh2uql5505tj83rperec.apps.googleusercontent.com',
    iosBundleId: 'com.example.easysave',
  );
}
